// Code generated by "generateGoNetworks.ts"; DO NOT EDIT.

package networks

var AllNetworks = []*Network{
	{
		ID: "furya",
		Currencies: []Currency{
			&NativeCurrency{
				Denom:       "ufury",
				CoinGeckoID: "fanfury",
				Decimals:    6,
			},
		},
	},
	{
		ID: "cosmos-hub",
		Currencies: []Currency{
			&NativeCurrency{
				Denom:       "uatom",
				CoinGeckoID: "cosmos",
				Decimals:    6,
			},
		},
	},
	{
		ID: "furya-testnet",
		Currencies: []Currency{
			&NativeCurrency{
				Denom:       "ufury",
				CoinGeckoID: "fanfury",
				Decimals:    6,
			},
		},
	},
	{
		ID: "cosmos-hub-theta",
		Currencies: []Currency{
			&NativeCurrency{
				Denom:       "uatom",
				CoinGeckoID: "cosmos",
				Decimals:    6,
			},
		},
	},
	{
		ID: "ethereum-goerli",
		Currencies: []Currency{
			&NativeCurrency{
				Denom:       "0x0000000000000000000000000000000000000000",
				CoinGeckoID: "ethereum",
				Decimals:    18,
			},
		},
	},
	{
		ID: "ethereum",
		Currencies: []Currency{
			&NativeCurrency{
				Denom:       "0x0000000000000000000000000000000000000000",
				CoinGeckoID: "ethereum",
				Decimals:    18,
			},
		},
	},
}
